/**
* Healthtech Suggester — Traditional Medicine Knowledge Base
 * Structured repository of diseases (vyadhi), pharmacological properties (karma),
 * dravyas (drugs/herbs) and yogas (formulations) referenced from classical texts.
 *
 * NOTE: For educational & research reference only. Not a substitute for
 * professional Ayurvedic or medical advice.
 */

const BOOKS = [
    "Charaka Samhita",
    "Sushruta Samhita",
    "Ashtanga Hridaya",
    "Bhavaprakasha",
    "Sharangadhara Samhita",
    "Ashtanga Sangraha",
];

const DISEASES = [
    { id: "jwara", name: "Jwara", sanskrit: "ज्वर", meaning: "Fever" },
    { id: "atisara", name: "Atisara", sanskrit: "अतिसार", meaning: "Diarrhea" },
    { id: "kasa", name: "Kasa", sanskrit: "कास", meaning: "Cough" },
    { id: "shwasa", name: "Shwasa", sanskrit: "श्वास", meaning: "Asthma / Dyspnea" },
    { id: "prameha", name: "Prameha", sanskrit: "प्रमेह", meaning: "Diabetes / Urinary disorders" },
    { id: "amlapitta", name: "Amlapitta", sanskrit: "अम्लपित्त", meaning: "Acidity / Hyperacidity" },
    { id: "arshas", name: "Arshas", sanskrit: "अर्शस्", meaning: "Hemorrhoids / Piles" },
    { id: "grahani", name: "Grahani", sanskrit: "ग्रहणी", meaning: "Malabsorption syndrome" },
    { id: "pandu", name: "Pandu", sanskrit: "पाण्डु", meaning: "Anemia" },
    { id: "kamala", name: "Kamala", sanskrit: "कामला", meaning: "Jaundice" },
    { id: "anidra", name: "Anidra", sanskrit: "अनिद्रा", meaning: "Insomnia" },
    { id: "chhardi", name: "Chhardi", sanskrit: "छर्दि", meaning: "Vomiting" },
    { id: "vata_vikara", name: "Vata Vikara", sanskrit: "वातविकार", meaning: "Vata disorders / Joint pain" },
    { id: "yakrit_vikara", name: "Yakrit Vikara", sanskrit: "यकृत् विकार", meaning: "Liver disorders" },
    { id: "kushta", name: "Kushta", sanskrit: "कुष्ठ", meaning: "Skin disorders" },
    { id: "netra_roga", name: "Netra Roga", sanskrit: "नेत्ररोग", meaning: "Eye disorders" },
];

const KARMAS = [
    { id: "deepana", name: "Deepana", meaning: "Appetizer / Stimulates agni" },
    { id: "pachana", name: "Pachana", meaning: "Digestive / Carminative" },
    { id: "vata_shamaka", name: "Vata Shamaka", meaning: "Pacifies Vata dosha" },
    { id: "pitta_shamaka", name: "Pitta Shamaka", meaning: "Pacifies Pitta dosha" },
    { id: "kapha_shamaka", name: "Kapha Shamaka", meaning: "Pacifies Kapha dosha" },
    { id: "rasayana", name: "Rasayana", meaning: "Rejuvenative / Immunomodulator" },
    { id: "vajikarana", name: "Vajikarana", meaning: "Aphrodisiac / Vitalizer" },
    { id: "jeervana", name: "Jeevaniya", meaning: "Nourishing / Energizing" },
    { id: "soothahara", name: "Shothahara", meaning: "Anti-inflammatory" },
    { id: "vedanasthapana", name: "Vedanasthapana", meaning: "Analgesic / Pain-relieving" },
    { id: "krimighna", name: "Krimighna", meaning: "Anthelmintic / Anti-parasitic" },
    { id: "mutra_virechana", name: "Mutra Virechana", meaning: "Diuretic" },
    { id: "vrishya", name: "Vrushya", meaning: "Spermatogenic / Aphrodisiac" },
    { id: "tvagdoshahara", name: "Tvagdoshahara", meaning: "Skin-disorder resolving" },
    { id: "chakshushya", name: "Chakshushya", meaning: "Beneficial for eyes" },
    { id: "medhya", name: "Medhya", meaning: "Nootropic / Brain tonic" },
];

const DRAVYAS = [
    {
        id: "tulsi",
        name: "Tulsi (Holy Basil)",
        sanskrit: "Surasa",
        latin: "Ocimum sanctum",
        taste: ["Katu", "Tikta"],
        virya: "Ushna (Hot)",
        book: ["Charaka Samhita"],
        karmas: ["Kapha Shamaka", "Vata Shamaka", "Deepana"],
        diseases: ["jwara", "kasa", "shwasa"],
        description: "One of the most revered herbs; used for fever (Jwara), respiratory complaints and as a general immunity booster.",
    },
    {
        id: "ashwagandha",
        name: "Ashwagandha (Winter Cherry)",
        sanskrit: "Ashwagandha",
        latin: "Withania somnifera",
        taste: ["Tikta", "Kashaya", "Madhura"],
        virya: "Ushna (Hot)",
        book: ["Charaka Samhita", "Sushruta Samhita"],
        karmas: ["Rasayana", "Vata Shamaka", "Vajikarana"],
        diseases: ["vata_vikara", "anidra"],
        description: "Chief Rasayana (rejuvenator) and adaptogen; calms Vata, supports sleep, strength and vitality.",
    },
    {
        id: "haritaki",
        name: "Haritaki (Chebulic Myrobalan)",
        sanskrit: "Haritaki, Abhaya",
        latin: "Terminalia chebula",
        taste: ["Kashaya", "Tikta", "Amala", "Katu", "Madhura"],
        virya: "Ushna (Hot)",
        book: ["Charaka Samhita", "Bhavaprakasha"],
        karmas: ["Deepana", "Pachana", "Rasayana", "Vata Shamaka"],
        diseases: ["grahani", "arshas", "amalaki_list"],
        description: "Regarded as the 'king of medicines'; mild laxative, digestive, and rejuvenative. A key Triphala component.",
    },
    {
        id: "amalaki",
        name: "Amalaki (Indian Gooseberry)",
        sanskrit: "Amalaki, Dhatri",
        latin: "Phyllanthus emblica",
        taste: ["Amala", "Madhura", "Tikta", "Kashaya"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita", "Ashtanga Hridaya"],
        karmas: ["Rasayana", "Pitta Shamaka", "Jeevaniya"],
        diseases: ["amlapitta", "rakta_pitta"],
        description: "A potent Rasayana and richest natural source of vitamin C; nourishes all tissues and pacifies Pitta.",
    },
    {
        id: "guduchi",
        name: "Guduchi / Giloy (Heart-leaved moonseed)",
        sanskrit: "Guduchi, Amrita",
        latin: "Tinospora cordifolia",
        taste: ["Tikta", "Kashaya", "Madhura"],
        virya: "Ushna (Hot)",
        book: ["Charaka Samhita", "Ashtanga Hridaya"],
        karmas: ["Rasayana", "Deepana", "Pachana", "Shothahara"],
        diseases: ["jwara", "pandu", "kamala", "amalaki_list"],
        description: "Known as 'Amrita' (nectar); antipyretic, immunomodulator for recurring fever and liver health.",
    },
    {
        id: "ginger",
        name: "Adrak / Shunti (Dry Ginger)",
        sanskrit: "Shunti, Ardraka",
        latin: "Zingiber officinale",
        taste: ["Katu", "Madhura"],
        virya: "Ushna (Hot)",
        book: ["Charaka Samhita", "Sushruta Samhita"],
        karmas: ["Deepana", "Pachana", "Kapha Shamaka", "Vata Shamaka"],
        diseases: ["chhardi", "kasa", "shwasa", "grahani"],
        description: "Universal household digestive; relieves nausea, cough and improves agni.",
    },
    {
        id: "pippali",
        name: "Pippali (Long Pepper)",
        sanskrit: "Pippali",
        latin: "Piper longum",
        taste: ["Katu", "Madhura"],
        virya: "Anushna - Shita (Lukewarm/Cool)",
        book: ["Charaka Samhita", "Sharangadhara Samhita"],
        karmas: ["Deepana", "Pachana", "Rasayana", "Kapha Shamaka"],
        diseases: ["kasa", "shwasa", "kasa"],
        description: "Bioavailability enhancer; prized for respiratory ailments and digestive fire.",
    },
    {
        id: "neem",
        name: "Nimba (Neem)",
        sanskrit: "Nimba",
        latin: "Azadirachta indica",
        taste: ["Tikta", "Kashaya"],
        virya: "Shita (Cold)",
        book: ["Sushruta Samhita", "Bhavaprakasha"],
        karmas: ["Krimighna", "Tvagdoshahara", "Pitta Shamaka"],
        diseases: ["kushta", "jwara", "prameha"],
        description: "Bitter blood-purifier; used for skin disorders, diabetes and parasitic infections.",
    },
    {
        id: "guduchi2",
        name: "Gokshura (Puncture Vine)",
        sanskrit: "Gokshura",
        latin: "Tribulus terrestris",
        taste: ["Madhura"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita", "Sushruta Samhita"],
        karmas: ["Mutra Virechana", "Vrushya", "Vajikarana"],
        diseases: ["prameha", "asthma"],
        description: "Renal tonic and diuretic; supports urinary health and male vitality.",
    },
    {
        id: "brahmi",
        name: "Brahmi (Water Hyssop / Bacopa)",
        sanskrit: "Brahmi",
        latin: "Bacopa monnieri",
        taste: ["Tikta", "Kashaya", "Madhura"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita", "Ashtanga Sangraha"],
        karmas: ["Medhya", "Rasayana"],
        diseases: ["anidra", "smriti_bhramsha"],
        description: "Exalted Medhya Rasayana; enhances memory, cognition and calms the mind.",
    },
    {
        id: "shatawari",
        name: "Shatavari (Asparagus)",
        sanskrit: "Shatavari",
        latin: "Asparagus racemosus",
        taste: ["Madhura", "Tikta"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita", "Ashtanga Hridaya"],
        karmas: ["Rasayana", "Jeevaniya", "Pitta Shamaka"],
        diseases: ["amlapitta", "shukra_kshaya"],
        description: "Principal female Rasayana; nourishing, coolant and galactagogue.",
    },
    {
        id: "kutki",
        name: "Kutki (Picrorhiza)",
        sanskrit: "Katuki",
        latin: "Picrorhiza kurroa",
        taste: ["Tikta"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita", "Bhavaprakasha"],
        karmas: ["Deepana", "Pachana", "Pitta Shamaka"],
        diseases: ["kamala", "yakrit_vikara", "jwara"],
        description: "Bitter hepatic-protective herb; a classical remedy for jaundice and liver disorders.",
    },
    {
        id: "bhringaraj",
        name: "Bhringaraj (False Daisy)",
        sanskrit: "Bhringaraja",
        latin: "Eclipta alba",
        taste: ["Tikta", "Katu", "Kashaya"],
        virya: "Ushna (Hot)",
        book: ["Bhavaprakasha", "Sushruta Samhita"],
        karmas: ["Rasayana", "Shothahara"],
        diseases: ["kamala", "kesha", "pandu"],
        description: "Hair, liver and skin tonic; used in jaundice and as a Rasayana.",
    },
    {
        id: "triphala_herbs",
        name: "Triphala (Three Fruits)",
        sanskrit: "Triphala",
        latin: "Haritaki + Amalaki + Bibhitaki",
        taste: ["Pancharasa"],
        virya: "Anushna (Lukewarm)",
        book: ["Charaka Samhita", "Sushruta Samhita"],
        karmas: ["Deepana", "Pachana", "Rasayana", "Chakshushya"],
        diseases: ["grahani", "arshas", "netra_roga", "amalaki_list"],
        description: "The classic tridosha-balancing blend; gentle bowel regulator and eye tonic.",
    },
    {
        id: "shatavari2",
        name: "Saindhava (Rock Salt)",
        sanskrit: "Saindhava Lavana",
        latin: "Rock salt",
        taste: ["Lavana"],
        virya: "Shita (Cold)",
        book: ["Charaka Samhita"],
        karmas: ["Deepana", "Pachana"],
        diseases: ["grahani", "shotha"],
        description: "Digestive mineral salt; improves taste and agni without provoking doshas.",
    },
];

const FORMULATIONS = [
    {
        id: "chyawanprash",
        name: "Chyawanprash",
        book: ["Charaka Samhita"],
        karmas: ["Rasayana", "Jeevaniya", "Vajikarana"],
        diseases: ["pandu", "kasa", "shwasa", "amalaki_list"],
        ingredients: ["Amalaki", "Ghee", "Honey", "Shatavari", "Pippali"],
        description: "The most celebrated Rasayana (rejuvenator) avaleha; Amalaki-based, boosts immunity, strength and longevity.",
    },
    {
        id: "triphala_churna",
        name: "Triphala Churna",
        book: ["Charaka Samhita", "Sushruta Samhita"],
        karmas: ["Deepana", "Pachana", "Rasayana", "Chakshushya"],
        diseases: ["grahani", "arshas", "netra_roga", "amalaki_list"],
        ingredients: ["Haritaki", "Bibhitaki", "Amalaki"],
        description: "Tridosha-balancing powder; gentle laxative, digestion and eye tonic.",
    },
    {
        id: "ashwagandha_churna",
        name: "Ashwagandha Churna",
        book: ["Charaka Samhita"],
        karmas: ["Rasayana", "Vata Shamaka", "Vajikarana"],
        diseases: ["vata_vikara", "anidra", "shukra_kshaya"],
        ingredients: ["Ashwagandha", "Milk", "Ghee"],
        description: "Vata-pacifying restorative powder for strength, sleep, and stamina.",
    },
    {
        id: "talisadi_churna",
        name: "Talisadi Churna",
        book: ["Sharangadhara Samhita"],
        karmas: ["Deepana", "Pachana", "Kapha Shamaka"],
        diseases: ["kasa", "shwasa", "chhardi", "kasa"],
        ingredients: ["Talisa Patra", "Pippali", "Shunti", "Elaichi", "Twak"],
        description: "Respiratory and digestive powder; excellent for cough, asthma and cold.",
    },
    {
        id: "sitopaladi_churna",
        name: "Sitopaladi Churna",
        book: ["Sharangadhara Samhita"],
        karmas: ["Deepana", "Kapha Shamaka"],
        diseases: ["kasa", "shwasa", "jwara"],
        ingredients: ["VamshaLochana", "Pippali", "Elaichi", "Twak", "Sugar"],
        description: "Gentle remedy for productive cough, fever and respiratory catarrh.",
    },
    {
        id: "lavangadi_vati",
        name: "Lavangadi Vati",
        book: ["Sharangadhara Samhita"],
        karmas: ["Deepana", "Pachana", "Kapha Shamaka"],
        diseases: ["chhardi", "kasa", "shwasa"],
        ingredients: ["Lavanga (Clove)", "Pippali", "Twak", "VamshaLochana"],
        description: "Chewable tablet for cough, nausea and loss of appetite.",
    },
    {
        id: "hingvashtaka_churna",
        name: "Hingvashtaka Churna",
        book: ["Sharangadhara Samhita"],
        karmas: ["Deepana", "Pachana", "Vata Shamaka"],
        diseases: ["grahani", "shula", "vata_vikara"],
        ingredients: ["Hingu", "Ajwain", "Shunti", "Pippali", "Saindhava", "Yavani"],
        description: "Classic digestive powder for abdominal distension, gas and Vata disorders.",
    },
    {
        id: "kutaja_ghana",
        name: "Kutaja Ghan Vati",
        book: ["Charaka Samhita"],
        karmas: ["Pachana", "Krimighna"],
        diseases: ["atisara", "grahani", "prameha"],
        ingredients: ["Kutaja bark", "Holarrhena antidysenterica"],
        description: "Specific classical remedy for diarrhea (Atisara) and amoebic dysentery.",
    },
    {
        id: "pachan_churna",
        name: "Pachan Churna",
        book: ["Charaka Samhita"],
        karmas: ["Deepana", "Pachana", "Kapha Shamaka"],
        diseases: ["grahani", "amlapitta", "shotha"],
        ingredients: ["Shunti", "Pippali", "Maricha", "Ajwain", "Haritaki"],
        description: "Digestive blend to kindle agni and relieve sluggish digestion.",
    },
    {
        id: "amalaki_rasayana",
        name: "Amalaki Rasayana",
        book: ["Charaka Samhita"],
        karmas: ["Rasayana", "Pitta Shamaka", "Jeevaniya"],
        diseases: ["pandu", "amlapitta", "rakta_pitta"],
        ingredients: ["Amalaki", "Ghee", "Honey"],
        description: "Pitta-pacifying rejuvenative preparation of Amalaki.",
    },
    {
        id: "kumaryasava",
        name: "Kumaryasava",
        book: ["Bhavaprakasha"],
        karmas: ["Deepana", "Pitta Shamaka", "Rasayana"],
        diseases: ["amlapitta", "rakta_pitta", "yakrit_vikara"],
        ingredients: ["Kumari (Aloe)", "Pippali", "Shunti", "Twak"],
        description: "Arista (fermented decoction) of Aloe; liver tonic, improves appetite and cools Pitta.",
    },
    {
        id: "ashokarishta",
        name: "Ashokarishta",
        book: ["Bhavaprakasha"],
        karmas: ["Pitta Shamaka", "Vata Shamaka"],
        diseases: ["ashrgdara", "rakta_pitta"],
        ingredients: ["Ashoka bark", "Dhataki", "Twak", "Pippali"],
        description: "Classic uterine tonic for women's health and menstrual disorders.",
    },
    {
        id: "shankh_bhasma",
        name: "Shankh Bhasma",
        book: ["Rasa Shastra tradition"],
        karmas: ["Deepana", "Pachana", "Pitta Shamaka"],
        diseases: ["amlapitta", "grahani", "chhardi"],
        ingredients: ["Shankha (Conch shell)"],
        description: "Mineral (bhasma) preparation for hyperacidity, ulcers and malabsorption.",
    },
    {
        id: "chitrakadi_vati",
        name: "Chitrakadi Vati",
        book: ["Sharangadhara Samhita"],
        karmas: ["Deepana", "Pachana", "Kapha Shamaka"],
        diseases: ["grahani", "amalaki_list", "shotha"],
        ingredients: ["Chitraka", "Pippali", "Shunti", "Haritaki"],
        description: "Potent digestive and appetizer; used in Grahani and loss of appetite.",
    },
    {
        id: "gokshuradi_guggulu",
        name: "Gokshuradi Guggulu",
        book: ["Bhavaprakasha"],
        karmas: ["Mutra Virechana", "Vata Shamaka", "Shothahara"],
        diseases: ["prameha", "vata_vikara", "mootrashmari"],
        ingredients: ["Gokshura", "Guggulu", "Trikatu", "Twak"],
        description: "Supports urinary tract, kidney health, and joint comfort.",
    },
    {
        id: "haridra_khanda",
        name: "Haridra Khanda",
        book: ["Bhavaprakasha"],
        karmas: ["Tvagdoshahara", "Pitta Shamaka", "Krimighna"],
        diseases: ["kushta", "prameha", "jwara"],
        ingredients: ["Haridra (Turmeric)", "Amla", "Kokilaksha", "Pippali"],
        description: "Turmeric-based formulation for skin complaints and diabetes.",
    },
    {
        id: "sarivadyasava",
        name: "Sarivadyasava",
        book: ["Bhavaprakasha"],
        karmas: ["Tvagdoshahara", "Rasayana"],
        diseases: ["kushta", "pandu", "jwara"],
        ingredients: ["Sariva", "Manjistha", "Guduchi", "Nimba"],
        description: "Blood-purifying arista for skin and chronic fevers.",
    },
    {
        id: "mahatriphala_ghrita",
        name: "Mahatriphala Ghrita",
        book: ["Ashtanga Hridaya"],
        karmas: ["Chakshushya", "Rasayana", "Pitta Shamaka"],
        diseases: ["netra_roga", "amalaki_list"],
        ingredients: ["Triphala", "Ghrita", "Pippali"],
        description: "Medicated ghee for eye health and vision; also useful in general debility.",
    },
    {
        id: "brahmi_ghrita",
        name: "Brahmi Ghrita",
        book: ["Charaka Samhita"],
        karmas: ["Medhya", "Rasayana"],
        diseases: ["anidra", "smriti_bhramsha", "apasmara"],
        ingredients: ["Brahmi", "Vacha", "Ghrita", "Kushtha"],
        description: "Medhya ghee for memory, cognition, and nervous system support.",
    },
    {
        id: "drakshavaleha",
        name: "Drakshavaleha",
        book: ["Ashtanga Hridaya"],
        karmas: ["Pitta Shamaka", "Rasayana"],
        diseases: ["kasa", "shwasa", "rakta_pitta"],
        ingredients: ["Draksha (Raisins)", "Pippali", "Honey", "Ghee"],
        description: "Nutritive linctus for dry cough, debility and Pitta-related respiratory dryness.",
    },
];

/**
 * Returns a disease object by id.
 */
function getDisease(id) {
    return DISEASES.find((d) => d.id === id);
}

/**
 * Returns a karma object by id.
 */
function getKarma(id) {
    return KARMAS.find((k) => k.id === id);
}

/**
 * Returns a display name for a book.
 */
function getBookName(book) {
    return book;
}
